### ISSUE TITLE
Update copyright year to 2018 (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/captain#11]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Captain

The DAV project you are looking at is the Captain. The captain is the logic that sits on board drones, gives it commands, negotiates missions with mission control, and communicates with the blockchain.

### The Issue

Update the copyright year from `2017` to `2018` in the `license` file at the root of the project.

### Contributing to Captain

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open [Captain GitHub page](https://github.com/DAVFoundation/captain) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/captain.git`
- [ ] **Make changes in the LICENSE file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/captain](https://github.com/YOUR-USER-NAME/captain)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#7`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by leaf-light** [comment]
I would like to do it.

**Comment by rishabh92** [comment]
I can change the year and look at how this project works.  😄

**Comment by Varunvaruns9** [comment]
I would like to do it

**Comment by cg-cnu** [comment]
Thanks for your interest @rishabh92 Sorry @Varunvaruns9 went ahead and raised the pr. Feel free to pick up issues in other repos. Or if you are interested in `captain` keep a watch on this one, as we will be creating more issues soon 😄 

Thanks for your work @Varunvaruns9 👍  Hope you got hooked on to opensource with this contribution 🙂 

Feel free to join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors) for more opportunities.

**Comment by cg-cnu** [comment]
Hey @rishabh92 If you are interested you can pick up this one https://github.com/DAVFoundation/xplore/issues/8 Its not open to public yet, I can assign it to you.

**Comment by rishabh92** [comment]
Hey @cg-cnu, I will keep a watch on captain project. Thanks!!
