### ISSUE TITLE
Add license badge

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/captain#7]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues here:
- [Missions](https://github.com/DAVFoundation/missions/labels/first-timers-only)
- [Mission Control](https://github.com/DAVFoundation/missioncontrol/labels/first-timers-only)
- [Captain](https://github.com/DAVFoundation/captain/labels/first-timers-only)

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Captain

The DAV project you are looking at is the Captain. The captain is the logic that sits on board drones, gives it commands, negotiates missions with mission control, and communicates with the blockchain.

### The Issue

Your task for this issue is...
In the [README.md](https://github.com/DAVFoundation/captain/blob/master/README.md) file 
add this following line of code:
````markdown
[![license](https://img.shields.io/github/license/DAVFoundation/captain.svg?style=flat-square)](https://github.com/DAVFoundation/captain/blob/master/LICENSE)`
````
This will display a badge like this: [![license](https://img.shields.io/github/license/DAVFoundation/captain.svg?style=flat-square)](https://github.com/DAVFoundation/captain/blob/master/LICENSE)

### Contributing to Captain

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Fork the repository from the [Captain GitHub page](https://github.com/DAVFoundation/captain).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/captain.git`
- [ ] **Make changes in the README.md file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/captain](https://github.com/YOUR-USER-NAME/captain)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#7`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

**Comment by bonecrushereb** [comment]
Hello cg-cnu,

I would love to work on this issue.

Thanks.

**Comment by cg-cnu** [comment]
Hey @bonecrushereb 
Thanks for your interest. These issues are meant for `first-timers`. Specially for folks who haven't done any open source contribution and looking for a simple way to do their first pull request. If you are are completely new to open source please do go ahead, else I would request you to leave it for the first-timers. Hope you understand. Thanks 😄

**Comment by TalAter** [comment]
Hi @bonecrushereb 

As @cg-cnu said. If this is the first time you are contributing to open source, we would be super-happy to have you! Go ahead.

**Comment by bonecrushereb** [comment]
Yes this is my first time thank you for the opportunity!

**Comment by cg-cnu** [comment]
License badge can be after the gitter chat. You can refer to other repos for consistency :smile:

**Comment by cg-cnu** [comment]
Hey @bonecrushereb Thanks for your help 👏💯 Congratulations on your first contribution to open source. 🎆 Hope this got you excited about contributing to open source 😄 Feel free to join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors)
